const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.NinePatch,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.right
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Tween: 0},
	{Character1: 0},
	{TextBox: 0},
	{StatesArr: 0},
	{StatesAJAX: 0},
	{TextSpeak: 0},
	{TextOption1: 0},
	{TextIcons: 0},
	{TextOption2: 0},
	{Keyboard: 0},
	{Character2: 0},
	{Fader: 0},
	{gameState: 0},
	{selection: 0},
	{points: 0},
	{TYPEWRITERSPEED: 0},
	{state: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Character1: class extends self.ISpriteInstance {},
	TextBox: class extends self.IWorldInstance {},
	StatesArr: class extends self.IArrayInstance {},
	StatesAJAX: class extends self.IInstance {},
	TextSpeak: class extends self.ITextInstance {},
	TextOption1: class extends self.ITextInstance {},
	TextIcons: class extends self.ISpriteInstance {},
	TextOption2: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Character2: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {}
}